/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUITransporte.java
 *
 * Created on 31/05/2010, 00:13:05
 */
package concesionaria;

import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author s
 */
public class GUITransporte extends javax.swing.JFrame {

  private Integer transporteSeleccionado;

  public Integer getTransporteSeleccionado() {
    return this.transporteSeleccionado;
  }

  /** Creates new form GUITransporte */
  public GUITransporte() {
    initComponents();
    this.setVisible(true);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    ListadoTransportes = new javax.swing.JList();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Seleccione Vehiculo de Transporte");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    ListadoTransportes.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    ListadoTransportes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    ListadoTransportes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        ListadoTransportesValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(ListadoTransportes);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void ListadoTransportesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListadoTransportesValueChanged

      //Relleno un atributo
      this.transporteSeleccionado = ListadoTransportes.getSelectedIndex();

      //Tratamiento encontrado en http://www.apl.jhu.edu/~hall/java/Swing-Tutorial/Swing-Tutorial-JList.html
      //JOptionPane.showMessageDialog(null, "Valor seleccionado" + ListadoTransportes.getSelectedValue().toString());
      //JOptionPane.showMessageDialog(null, "Valor seleccionado" + ListadoTransportes.getSelectedIndex());


    }//GEN-LAST:event_ListadoTransportesValueChanged

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new GUITransporte().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JList ListadoTransportes;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
